global:
  resolve_timeout: 5m

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  receiver: rocketchat
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: rocketchat
    webhook_configs:
      - url: "http://rocketchat:3000/hooks/<WEBHOOK_ID>/<TOKEN>"
        send_resolved: true
        http_config: {}
        max_alerts: 10
