version: '3.8'

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat
    container_name: rockerchat  
    restart: unless-stopped
    ports:
      - "4000:3000"
    environment:
      - ROOT_URL=http://localhost:4000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - DEPLOY_METHOD=docker  
    depends_on:
      - mongo
    networks:
      - monitoring

  mongo:
    image: mongo:7.0
    container_name: mongorocket  
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - monitoring

volumes:
  mongo-data:

networks:
  monitoring:
    external: true
